### ISSUE TITLE
Nerodo kalbos pasirinkimo

### ISSUE THREAD

**Issue by Rimdov** [gntvls/mybb-ltu#1]
Sveiki, parsisiunčiau šitą kalbos packą, bet adminkėj nerodo, kad jis būtų. Kažko gal trūksta ar kažko nedarariau ? Ar galbūt turi būti tam tikra mybb versija kuri palaiko sulietuvinimą :) ?

**Comment by gntvls** [comment]
Sveiki, aš naudoju MyBB 1.8.7 versiją: https://f1news.lt/forum . 
Ne viskas čia išversta , bet pagrindas yra. Ir turėtų veikti

**Comment by Rimdov** [comment]
Haha, man rodos jums ir per jūsų portalą rašiau. Aš turiu 1.8.11 ir matau tik https://i.gyazo.com/a8ab3757dac124de66ad184f08f9f4c7.png
Galbūt čia trūksta kokia lithuanian.php failiuko
https://i.gyazo.com/8fe2a93f6a07410aca5cf5bf56288f13.png

**Comment by gntvls** [comment]
Teisingai, reikia įdėti failiuką lithuanian.php į čia: `/public_html/forum/inc/languages/lithuanian.php` 

lithuanian.php failiuko turinys:
`<?php
/**
 * MyBB 1.8 Lithuanian Language Pack
 * Copyright 2014 MyBB Group, All Rights Reserved
 *
 */

// The friendly name of the language
$langinfo['name'] = "Lietuvių";

// The author of the language
$langinfo['author'] = "Marius G.";

// The language authors website
$langinfo['website'] = "http://www.f1news.lt";

// Compatible version of MyBB
$langinfo['version'] = "1807";

// Sets if the translation includes the Admin CP (1 = yes, 0 = no)
$langinfo['admin'] = 1;

// Sets if the language is RTL (Right to Left) (1 = yes, 0 = no)
$langinfo['rtl'] = 0;

// Sets the lang in the <html> on all pages
$langinfo['htmllang'] = "lt";

// Sets the character set, blank uses the default.
$langinfo['charset'] = "UTF-8";
`

Šiaip nusikopijuok iš English.php ir pasidaryk savo failiuką, turėtų tada veikti.

**Comment by Rimdov** [comment]
Va dabar viskas veikia :) , dėkuj už pagalbą ;) . Jei kažką užmatysiu kas neišversta būtinai pasistengsiu kažką updeitinti ir čia ;) . PS: galbūt būtų naudingą tą failiuką irgi įkelti čia jeigu kažkam ateityje irgi reiktu :) .

**Comment by gntvls** [comment]
Sėkmės. Įkelsiu ir pagrindinį failiuką
